project:
  type: website

website:
  title: "Personal Web"
  navbar:
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - work.qmd
      - blog.qmd
  page-footer: "Copyright 2025, Xu Chen"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



